### ISSUE TITLE
Interest in making this completely client side ?

### ISSUE THREAD

**Issue by agnivade** [disintegration/bebop#1]
Hi there !

Great project. I was thinking of making this a completely client-side app with service workers, localstorage, material-ui design and just using firebase as the backend.

So, that will completely remove the Golang server component(which I understand has undergone a lot of effort into building). Is this something that you will be willing to do ?

**Comment by disintegration** [comment]
Hello,

No, in this project I'm mostly interested in the Go backend development. From your description i think that you are going to build a completely different application, because Go code as of now is 85% of the repository codebase.

**Comment by agnivade** [comment]
Sure, I guessed as much. Thanks anyways !
