### ISSUE TITLE
plugins: devise a way to add a plugin mechanism

### ISSUE THREAD

**Issue by sbinet** [disintegration/bebop#5]
it would be nice if `bebop` had a way to allow 3rd-party plugins to extend or modify `bebop` behaviour.
for example, I'd like to be able to have `bebop` being to send an email whenever a new post is created in a topic.
this could perhaps be implemented with plugins.

most probably, if plugins are blessed as the `bebop` way to achieve extension and modification, they would need to be re-compiled together with the "main" application.

**Comment by CanRau** [comment]
maybe as separate programs like talked about here https://www.reddit.com/r/golang/comments/7ub10v/any_discourselike_forum_in_go/#t1_dtrs55r

**Comment by kpym** [comment]
My be Go native plugins could be used here: https://golang.org/pkg/plugin/.

**Comment by kpym** [comment]
@sbinet why you close this issue ? Is this already resolved ?
