### ISSUE TITLE
Troubles in signup

### ISSUE THREAD

**Issue by qtopie** [disintegration/bebop#9]
![image](https://user-images.githubusercontent.com/11538418/37693147-b715510a-2cf8-11e8-9e6e-53b5da18d2bb.png)

Cannot expand the signup menu after setup.

**Comment by disintegration** [comment]
Hello,

The sign-in system uses the oauth2 protocol. Have you configured at least one of the oauth providers (google, facebook or github)? These settings are located inside the "oauth" section of the configuration file ("bebop.conf").

**Comment by qtopie** [comment]
Okay, maybe this should be added in documentation. Does it support other oauth provider?

**Comment by disintegration** [comment]
> Okay, maybe this should be added in documentation.

It's mentioned in the "Getting Started" section of the readme (see the second bullet point "Obtain OAuth 2.0 credentials..."). Maybe I should add more information on this.

> Does it support other oauth provider?

For now only these three providers are supported (google, facebook, github).
